<?php
$ok = !empty($dashboard['ok']);
$header = (array)($dashboard['header'] ?? []); $rows = (array)($dashboard['rows'] ?? []);
$summary = (array)($dashboard['summary'] ?? []); $accounts = (array)($dashboard['accounts'] ?? []);
$reconDate = (string)($dashboard['reconciliation_date'] ?? date('Y-m-d'));
$revenueDate = (string)($dashboard['revenue_date'] ?? date('Y-m-d', strtotime('-1 day')));
$headerId = (int)($header['id'] ?? 0); $canEdit = !empty($can_reconcile_edit);
$money = static fn($v) => 'Rp ' . number_format((float)$v, 0, ',', '.');
?>
<style>
  .revenue-recon{--wine:#9d252b;--ink:#172033;--line:#e8e1de}.rr-head{display:flex;justify-content:space-between;gap:1rem;align-items:end;margin-bottom:1rem}.rr-head h4{font-weight:850;color:var(--ink);margin:0}.rr-head p{font-size:.78rem;color:#6d7280;margin:.3rem 0 0}.rr-filter{display:flex;gap:.55rem;align-items:end;background:#fff;border:1px solid var(--line);padding:.7rem;border-radius:12px}.rr-filter label{display:block;font-size:.65rem;font-weight:800;color:#6c6260}.rr-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem;margin-bottom:1rem}.rr-stat{background:#fff;border:1px solid var(--line);border-radius:13px;padding:.8rem}.rr-stat span{font-size:.64rem;font-weight:800;text-transform:uppercase;color:#827975}.rr-stat strong{display:block;font-size:1.05rem;color:var(--ink);margin-top:.25rem}.rr-help{background:#fff8ef;border:1px solid #f2dcc0;color:#654f36;border-radius:12px;padding:.75rem .9rem;font-size:.74rem;margin-bottom:1rem}.rr-method{background:#fff;border:1px solid var(--line);border-radius:14px;margin-bottom:.7rem;overflow:hidden}.rr-method-head{display:flex;justify-content:space-between;align-items:center;padding:.75rem .9rem;background:#fffdfc;border-bottom:1px solid #f1e9e5}.rr-method-name{font-weight:850;color:var(--ink)}.rr-method-meta{font-size:.67rem;color:#7b7370}.rr-badge{font-size:.62rem;font-weight:850;padding:.25rem .45rem;border-radius:99px;background:#eef1f5}.rr-badge.MATCHED,.rr-badge.POSTED{color:#087452;background:#e6f7ef}.rr-badge.OPEN{color:#a45b00;background:#fff0da}.rr-grid{display:grid;grid-template-columns:1fr 1.15fr 1fr 2.2fr}.rr-cell{padding:.8rem;border-right:1px solid #f0e9e5}.rr-cell:last-child{border:0}.rr-label{font-size:.61rem;text-transform:uppercase;font-weight:850;color:#817773;margin-bottom:.3rem}.rr-value{font-weight:850;color:var(--ink)}.rr-note{font-size:.64rem;color:#858087;margin-top:.2rem}.rr-actions{display:grid;grid-template-columns:1.15fr .9fr 1.3fr auto;gap:.45rem;align-items:end}.rr-actions label{font-size:.61rem;font-weight:800;color:#746c69}.rr-actions label span{display:block;margin-bottom:.2rem}.rr-toast{position:fixed;right:1rem;bottom:1rem;background:#172033;color:#fff;padding:.75rem 1rem;border-radius:10px;display:none;z-index:1090}.rr-toast.error{background:#a61f28}.rr-history{margin-top:1rem;background:#fff;border:1px solid var(--line);border-radius:13px;padding:.8rem}.rr-history a{font-weight:750;color:var(--wine);text-decoration:none}@media(max-width:900px){.rr-head{align-items:stretch;flex-direction:column}.rr-filter{flex-wrap:wrap}.rr-summary{grid-template-columns:1fr 1fr}.rr-grid{display:block}.rr-cell{border-right:0;border-bottom:1px solid #f0e9e5}.rr-actions{grid-template-columns:1fr 1fr}.rr-actions .rr-note-input{grid-column:1/-1}}@media(max-width:520px){.rr-summary{grid-template-columns:1fr 1fr}.rr-filter>div{flex:1;min-width:135px}.rr-actions{grid-template-columns:1fr}.rr-actions .rr-note-input{grid-column:auto}}
</style>
<div class="page-wrapper revenue-recon"><div class="container-xl py-3">
  <?php $this->load->view('finance/_tabs', ['finance_tab_active'=>'revenue-reconciliation']); ?>
  <div class="rr-head"><div><h4><i class="ri-hand-coin-line text-danger"></i> Rekonsiliasi Pendapatan</h4><p>Cocokkan omzet POS dengan dana settlement per metode pembayaran, bukan per rekening.</p></div>
    <form class="rr-filter" method="get"><div><label>Tanggal rekonsiliasi</label><input class="form-control form-control-sm" type="date" name="date" max="<?= date('Y-m-d') ?>" value="<?= html_escape($reconDate) ?>"></div><div><label>Pendapatan tanggal</label><input class="form-control form-control-sm" type="date" name="revenue_date" max="<?= html_escape($reconDate) ?>" value="<?= html_escape($revenueDate) ?>"></div><button class="btn btn-sm btn-primary">Tampilkan</button><?php if($canEdit): ?><button class="btn btn-sm btn-outline-primary" type="button" id="rr-new">Sesi Baru</button><?php endif; ?></form>
  </div>
  <?php if(!$ok): ?><div class="alert alert-danger"><?= html_escape((string)($dashboard['message'] ?? 'Modul belum siap.')) ?></div><?php else: ?>
  <div class="rr-summary"><div class="rr-stat"><span>Omzet POS</span><strong><?= $money($summary['expected_total'] ?? 0) ?></strong></div><div class="rr-stat"><span>Settlement Diinput</span><strong><?= $money($summary['actual_total'] ?? 0) ?></strong></div><div class="rr-stat"><span>Selisih Bersih</span><strong><?= $money($summary['difference_total'] ?? 0) ?></strong></div><div class="rr-stat"><span>Progres</span><strong><?= (int)($summary['checked'] ?? 0) ?>/<?= count($rows) ?> metode</strong></div></div>
  <div class="rr-help"><b>Alur:</b> angka omzet dibaca dari pembayaran lunas pada tanggal pendapatan. Isi jumlah bersih yang benar-benar diterima. Jika berbeda karena MDR, komisi, pajak, atau koreksi provider, simpan lalu posting selisih. Posting memperbarui kas berjalan pada tanggal rekonsiliasi tanpa menggandakan omzet.</div>
  <?php foreach($rows as $row): $posted=(string)$row['status']==='POSTED'; $actual=$row['actual_amount']; $diff=$row['difference_amount']; ?>
  <article class="rr-method"><div class="rr-method-head"><div><div class="rr-method-name"><?= html_escape((string)$row['method_name']) ?></div><div class="rr-method-meta"><?= html_escape((string)$row['method_type']) ?> · <?= (int)$row['transaction_count'] ?> transaksi · pendapatan <?= html_escape(date('d/m/Y', strtotime($revenueDate))) ?></div></div><span class="rr-badge <?= html_escape((string)$row['status']) ?>"><?= html_escape((string)$row['status']) ?></span></div>
    <form class="rr-line"><input type="hidden" name="reconciliation_id" value="<?= $headerId ?>"><input type="hidden" name="reconciliation_date" value="<?= html_escape($reconDate) ?>"><input type="hidden" name="revenue_date" value="<?= html_escape($revenueDate) ?>"><input type="hidden" name="payment_method_id" value="<?= (int)$row['payment_method_id'] ?>"><input type="hidden" name="line_id" value="<?= (int)$row['line_id'] ?>">
    <div class="rr-grid"><div class="rr-cell"><div class="rr-label">Omzet menurut POS</div><div class="rr-value"><?= $money($row['expected_amount']) ?></div><div class="rr-note">Pembayaran PAID, final + deposit.</div></div>
    <div class="rr-cell"><div class="rr-label">Settlement riil diterima</div><input class="form-control form-control-sm" name="actual_amount" inputmode="decimal" placeholder="0" value="<?= $actual===null?'':html_escape(number_format((float)$actual,0,',','.')) ?>" <?= (!$canEdit||$posted)?'disabled':'' ?>></div>
    <div class="rr-cell"><div class="rr-label">Selisih settlement − omzet</div><div class="rr-value"><?= $actual===null?'—':$money($diff) ?></div><div class="rr-note"><?= $actual===null?'Belum diperiksa':((float)$diff<0?'Potongan/kurang diterima':((float)$diff>0?'Lebih diterima':'Sesuai')) ?></div></div>
    <div class="rr-cell"><div class="rr-actions"><label><span>Rekening settlement</span><select class="form-select form-select-sm" name="account_id" <?= (!$canEdit||$posted)?'disabled':'' ?>><option value="">Pilih rekening</option><?php foreach($accounts as $account): ?><option value="<?= (int)$account['id'] ?>" <?= (int)$row['account_id']===(int)$account['id']?'selected':'' ?>><?= html_escape((string)$account['account_name']) ?></option><?php endforeach; ?></select></label><label><span>Tindakan</span><select class="form-select form-select-sm" name="resolution_type" <?= (!$canEdit||$posted)?'disabled':'' ?>><option value="NONE">Biarkan terbuka</option><option value="OUT" <?= (string)($row['resolution_type']??'')==='OUT'?'selected':'' ?>>Mutasi keluar</option><option value="IN" <?= (string)($row['resolution_type']??'')==='IN'?'selected':'' ?>>Mutasi masuk</option></select></label><label class="rr-note-input"><span>Catatan selisih</span><input class="form-control form-control-sm" name="resolution_note" value="<?= html_escape((string)($row['resolution_note']??'')) ?>" placeholder="MDR/komisi/pajak" <?= (!$canEdit||$posted)?'disabled':'' ?>></label><div><?php if($canEdit&&!$posted): ?><button class="btn btn-sm btn-outline-primary rr-save" type="button">Simpan</button><?php if((int)$row['line_id']>0 && abs((float)$diff)>=.005): ?><button class="btn btn-sm btn-primary rr-post" type="button">Posting</button><?php endif; ?><?php else: ?><span class="small text-success"><?= $posted?'Sudah dimutasi':'' ?></span><?php endif; ?></div></div></div></div></form>
  </article><?php endforeach; ?>
  <div class="rr-history"><b>Riwayat sesi</b><div class="d-flex flex-wrap gap-3 mt-2"><?php foreach((array)($dashboard['recent']??[]) as $item): ?><a href="?<?= html_escape(http_build_query(['date'=>$item['reconciliation_date'],'revenue_date'=>$item['revenue_date'],'reconciliation_id'=>$item['id']])) ?>"><?= html_escape((string)$item['reconciliation_no']) ?> (<?= html_escape((string)$item['status']) ?>)</a><?php endforeach; ?></div></div>
  <?php endif; ?>
</div></div><div class="rr-toast" id="rr-toast"></div>
<script>
(function(){const saveUrl=<?= json_encode($save_url) ?>,postUrl=<?= json_encode($post_url) ?>,roundUrl=<?= json_encode($round_create_url) ?>;const toast=(m,e)=>{const x=document.getElementById('rr-toast');x.textContent=m;x.className='rr-toast '+(e?'error':'');x.style.display='block';setTimeout(()=>x.style.display='none',3500)};const send=(url,data)=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(data)}).then(async r=>{const j=await r.json();if(!r.ok||!j.ok)throw Error(j.message||'Proses gagal');return j});document.querySelectorAll('.rr-save').forEach(b=>b.onclick=()=>{const f=b.closest('form'),data=Object.fromEntries(new FormData(f));b.disabled=true;send(saveUrl,data).then(j=>{toast(j.message);location.reload()}).catch(e=>{toast(e.message,true);b.disabled=false})});document.querySelectorAll('.rr-post').forEach(b=>b.onclick=()=>{if(!confirm('Posting selisih ke kas berjalan? Tindakan ini membuat mutasi rekening.'))return;const f=b.closest('form');b.disabled=true;send(postUrl,{line_id:f.querySelector('[name=line_id]').value}).then(j=>{toast(j.message);location.reload()}).catch(e=>{toast(e.message,true);b.disabled=false})});const n=document.getElementById('rr-new');if(n)n.onclick=()=>{send(roundUrl,{reconciliation_date:document.querySelector('[name=date]').value,revenue_date:document.querySelector('[name=revenue_date]').value}).then(j=>location.href=j.redirect_url).catch(e=>toast(e.message,true))}})();
</script>
