<?php
$installation = is_array($installation ?? null) ? $installation : [];
$license = is_array($license ?? null) ? $license : [];
$active = strtoupper((string)($installation['activation_status'] ?? 'UNACTIVATED'));
?>
<div class="container-fluid py-3">
  <div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><h4 class="mb-1">Lisensi &amp; Aktivasi</h4><p class="text-muted mb-0">Status entitlement lokal tanpa menampilkan token atau rahasia penerbit.</p></div><span class="badge <?= ($mode ?? '') === 'ENFORCE' ? 'text-bg-warning' : 'text-bg-info' ?> p-2">Mode <?= html_escape((string)($mode ?? 'AUDIT_ONLY')) ?></span></div>
  <?php if (($mode ?? 'AUDIT_ONLY') !== 'ENFORCE'): ?><div class="alert alert-success"><i class="ri-shield-check-line me-1"></i><strong>Mode pemantauan aktif.</strong> Fondasi lisensi sudah mencatat keputusan FeatureGate, tetapi tidak menolak POS, laporan, maupun data pada staging ini.</div><?php endif; ?>
  <div class="alert <?= !empty($verification['verified']) ? 'alert-info' : 'alert-warning' ?>"><strong>Verifikasi tanda tangan Control:</strong> <?= html_escape((string)($verification['status'] ?? 'UNCONFIGURED')) ?><div class="small mt-1"><?= html_escape((string)($verification['code'] ?? 'DEPLOYMENT_TRUST_NOT_CONFIGURED')) ?>. Status VERIFIED pada tabel lokal saja tidak cukup; dokumen harus cocok dengan kunci publik Control dan identitas instalasi yang disiapkan admin server. Mode pemantauan tetap tidak memblokir kasir.</div></div>
  <div class="row g-3 mb-3"><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">Instalasi</div><div class="fw-semibold mt-1"><?= html_escape($active) ?></div><div class="small text-muted mt-2">ID instalasi akan dibuat saat alur aktivasi Control Center dijalankan.</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">Lisensi lokal</div><div class="fw-semibold mt-1"><?= html_escape((string)($license['verification_status'] ?? 'BELUM ADA')) ?></div><div class="small text-muted mt-2">Edisi: <?= html_escape((string)($license['edition_code'] ?? '-')) ?></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">Maintenance</div><div class="fw-semibold mt-1"><?= html_escape((string)($license['maintenance_ends_at'] ?? '-')) ?></div><div class="small text-muted mt-2">Berakhirnya maintenance tidak boleh menghentikan transaksi atau akses data.</div></div></div></div></div>
  <div class="card"><div class="card-header fw-semibold">Katalog fitur aplikasi</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Fitur</th><th>Kategori</th><th>Keputusan saat ini</th></tr></thead><tbody><?php foreach ((array)($features ?? []) as $feature): ?><tr><td><div class="fw-semibold"><?= html_escape((string)$feature['name']) ?></div><small class="text-muted"><?= html_escape((string)$feature['code']) ?></small></td><td><?= html_escape((string)$feature['category']) ?></td><td><span class="badge text-bg-secondary"><?= html_escape((string)($feature['decision']['code'] ?? 'UNKNOWN')) ?></span></td></tr><?php endforeach; ?></tbody></table></div></div>
  <div class="alert alert-light border mt-3 mb-0 small"><strong>Tahap berikutnya sebelum enforcement:</strong> paket customer signed, kunci publik penerbit, aktivasi online/offline, pairing terminal, serta uji internet putus. Tidak ada tombol lokal untuk menaikkan paket karena entitlement harus berasal dari payload bertanda tangan.</div>
</div>
